name: Fetch Market Snapshot

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * 1-5'
    - cron: '0 2 * * 1-5'
    - cron: '30 2 * * 1-5'
    - cron: '0 3 * * 1-5'
    - cron: '30 3 * * 1-5'
    - cron: '30 5 * * 1-5'
    - cron: '0 6 * * 1-5'
    - cron: '40 6 * * 1-5'
    - cron: '0 7 * * 1-5'

jobs:
  fetch:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch market snapshot
        env:
          PYTHONPYCACHEPREFIX: /tmp
        run: python src/fetch_market_data.py

      - name: Commit data snapshot
        run: |
          if git diff --quiet --exit-code; then
            echo "No changes to commit"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data
          git commit -m "chore: update market snapshot $(date -u +'%%Y-%%m-%%d %%H:%%M UTC')"
          git push
